Repository Arquisoft/lomap_en2b, pull requests merged in 2023-05, with the labels that each got.

#138 Front improvement
  webapp/src/pages/addLandmark/AddLandmark.tsx
  webapp/src/pages/addLandmark/addLandmark.css
  webapp/src/pages/addLandmark/solidLandmarkManagement.tsx
  webapp/src/shared/shareddtypes.ts
Labels: enhancement :heavy_plus_sign:

#140 Added the page to filter and review landmarks
  webapp/src/pages/addLandmark/solidLandmarkManagement.tsx
  webapp/src/pages/home/Home.tsx
  webapp/src/pages/otherUsersLandmark/LandmarkFriend.tsx
  webapp/src/shared/shareddtypes.ts
Labels: enhancement :heavy_plus_sign:

#141 solidLandmarkManagement
  webapp/src/pages/addLandmark/solidLandmarkManagement.tsx
Labels: bug :gear:

#143 Fixing conflicts v2
  webapp/src/pages/otherUsersLandmark/LandmarkFriend.tsx
Labels: bug :gear:

#145 Puesto el SolidHelper dentro de src para poder importarlo
  webapp/src/pages/addLandmark/AddLandmark.tsx
  webapp/src/pages/home/Home.tsx
  webapp/src/pages/otherUsersLandmark/LandmarkFriend.tsx
  webapp/src/solidHelper/solidLandmarkManagement.tsx
  webapp/tsconfig.json
Labels: bug :gear:

#147 Cambio de formato
  webapp/src/pages/addLandmark/AddLandmark.tsx
  webapp/src/pages/home/Home.tsx
  webapp/src/pages/otherUsersLandmark/LandmarkFriend.tsx
  webapp/src/solidHelper/solidLandmarkManagement.tsx
Labels: enhancement :heavy_plus_sign:

#149 More tests added (landmarkFriend)
  webapp/src/pages/otherUsersLandmark/LandmarkFriend.tsx
  webapp/src/test/LandmarkFriend.test.tsx
  webapp/src/test/Leftbar.test.tsx
  webapp/src/test/Navbar.test.tsx
Labels: Testing

#150 The closest to running e2e
  webapp/e2e/features/find-friends.feature
  webapp/e2e/features/friends-list.feature
  webapp/e2e/features/profile.feature
  webapp/e2e/features/see-landmarks.feature
  webapp/e2e/jest.config.ts
  webapp/e2e/steps/add-landmark.steps.ts
  webapp/e2e/steps/find-friends.steps.ts
  webapp/e2e/steps/friends-list.steps.ts
  webapp/e2e/steps/profile.steps.ts
  webapp/e2e/steps/see-landmarks.steps.ts
  webapp/package-lock.json
  webapp/package.json
Labels: Testing

#152 Removed references to a currently non-existent persistence layer.
  docs/04_solution_strategy.adoc
  docs/05_building_block_view.adoc
  webapp/tsconfig.json
Labels: documentation :scroll:

#157 Change on the domain model (Section 8)
  docs/08_concepts.adoc
Labels: enhancement :heavy_plus_sign:

#164 Little error fix
  webapp/src/pages/addLandmark/AddLandmark.tsx
Labels: bug :gear:

#166 littleFixImageDonWork
  webapp/src/pages/addLandmark/AddLandmark.tsx
Labels: bug :gear:
