Repository Arquisoft/lomap_en2b, pull requests merged in 2023-02, with the labels that each got.

#16 Doc section6 diego
  docs/06_runtime_view.adoc
Labels: documentation

#17 Documentation part 8 - Concepts
  docs/08_concepts.adoc
Labels: documentation

#18 First draft of the documentation section 4
  docs/04_solution_strategy.adoc
Labels: documentation

#21 Docu seccion9
  docs/09_design_decisions.adoc
Labels: documentation

#20 Added the point 10 of the documentation
  docs/10_quality_scenarios.adoc
Labels: documentation

#23 Finished part 3 of document. Missing part 7
  README.md
  docs/03_system_scope_and_context.adoc
  docs/images/Captura de pantalla 2023-02-20 164603.jpg
  docs/images/UseCaseASW.drawio.png
Labels: documentation

#26 Readme clean up
  Deployment.md
  QuickstartGuide.md
  README.md
Labels: enhancement

#27 Documentation part 7
  .gitignore
  docs/07_deployment_view.adoc
Labels: documentation

#25 Added N-Tier architecture and MVC to the glossary
  docs/12_glossary.adoc
Labels: documentation

#29 First deliverable of the documentation
  images/Captura de pantalla 2023-02-20 164603.jpg
  images/Deployment diagram.png
  images/Sequence diagram.png
  images/UML diagram.png
  images/Use case diagram.png
  images/UseCaseASW.drawio.png
  index.html
Labels: documentation :scroll:

#34 Errors doc part3
  docs/03_system_scope_and_context.adoc
  docs/images/BusinessContext.png
Labels: bug :gear:, documentation :scroll:

#35 Added HappySw to the list of Stakeholders
  docs/01_introduction_and_goals.adoc
Labels: documentation :scroll:

#36 Fixed the diagrams from parts 5, 7, 10 and 11
  docs/05_building_block_view.adoc
  docs/07_deployment_view.adoc
  docs/11_technical_risks.adoc
Labels: documentation :scroll:

#33 Correction of mistakes Docs0.1
  docs/02_architecture_constraints.adoc
  docs/04_solution_strategy.adoc
  docs/09_design_decisions.adoc
Labels: bug :gear:, documentation :scroll:

#38 Develop into master to create release
  docs/01_introduction_and_goals.adoc
  docs/02_architecture_constraints.adoc
  docs/03_system_scope_and_context.adoc
  docs/04_solution_strategy.adoc
  docs/05_building_block_view.adoc
  docs/06_runtime_view.adoc
  docs/07_deployment_view.adoc
  docs/09_design_decisions.adoc
  docs/11_technical_risks.adoc
  docs/images/BusinessContext.png
Labels: documentation :scroll:
