Repository Arquisoft/lomap_en2b, pull requests merged in 2023-03, with the labels that each got.

#43 Added the map
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/components/map/Map.css
  webapp/src/components/map/Map.tsx
Labels: enhancement :heavy_plus_sign:

#44 Added the basic pages and components
  restapi/package-lock.json
  restapi/package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/components/navbar/Navbar.tsx
  webapp/src/components/navbar/navbar.css
  webapp/src/pages/home/Home.tsx
  webapp/src/pages/home/home.css
  webapp/src/pages/login/Login.tsx
  webapp/src/pages/login/login.css
  webapp/src/pages/register/Register.tsx
  webapp/src/pages/register/register.css
Labels: enhancement :heavy_plus_sign:

#48 New types
  webapp/src/shared/shareddtypes.ts
Labels: enhancement :heavy_plus_sign:, help wanted :sos:

#49 Feature map improvement
  webapp/src/components/EmailForm.tsx
  webapp/src/components/map/Map.tsx
  webapp/src/shared/shareddtypes.ts
Labels: enhancement :heavy_plus_sign:

#53 Profile page stopped to solve problems with solid
  webapp/src/components/rightbar/UserRightBar.tsx
  webapp/src/components/rightbar/userRightBar.css
  webapp/src/pages/profile/Profile.tsx
Labels: enhancement :heavy_plus_sign:

#55 Added some of the final touches it is still unfinished
  webapp/public/noAvatar.png
  webapp/src/App.tsx
  webapp/src/components/leftBar/leftBar.css
  webapp/src/components/rightbar/UserRightBar.tsx
  webapp/src/components/rightbar/userRightBar.css
  webapp/src/pages/profile/Profile.tsx
  webapp/src/pages/profile/profile.css
Labels: enhancement :heavy_plus_sign:

#57 Searching for users (no css)
  package-lock.json
  restapi/.env
  restapi/api.ts
  restapi/models/User.ts
  restapi/package-lock.json
  restapi/package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/navbar/Navbar.tsx
  webapp/src/pages/users/Users.tsx
  webapp/src/pages/users/users.css
  webapp/src/shared/shareddtypes.ts
  webapp/src/unused/EmailForm.tsx
  webapp/src/unused/UserList.test.tsx
  webapp/src/unused/UserList.tsx
Labels: enhancement :heavy_plus_sign:

#60 Add markers temporal solution
  webapp/src/App.tsx
  webapp/src/components/leftBar/LeftBar.tsx
  webapp/src/components/map/Map.css
  webapp/src/components/map/Map.tsx
  webapp/src/components/map/MapMarker.tsx
  webapp/src/pages/addLandmark/AddLandmark.tsx
  webapp/src/pages/addLandmark/addLandmark.css
  webapp/src/pages/home/home.css
  webapp/src/pages/profile/Profile.tsx
Labels: enhancement :heavy_plus_sign:

#69 Updated the README with the feedback from last week
  .gitignore
  OtherInformation.md
  QuickstartGuide.md
  README.md
  README_es.md
  webapp/README.md
Labels: documentation :scroll:, enhancement :heavy_plus_sign:

#68 Updated points 7 and 11. Point 10 remains the same
  docs/07_deployment_view.adoc
  docs/11_technical_risks.adoc
Labels: documentation :scroll:, enhancement :heavy_plus_sign:

#75 Now any pod provider can be used, as long as the URL introduced is OK
  restapi/api.ts
  restapi/package-lock.json
  restapi/package.json
  webapp/package-lock.json
  webapp/src/pages/login/Login.tsx
Labels: enhancement :heavy_plus_sign:
