Repository Arquisoft/lomap_en2b, pull requests merged in 2023-04, with the labels that each got.

#79 Actualización de la documentación
  docs/01_introduction_and_goals.adoc
  docs/06_runtime_view.adoc
  docs/08_concepts.adoc
Labels: documentation :scroll:

#80 Pedro documentation1.0
  docs/04_solution_strategy.adoc
  docs/09_design_decisions.adoc
Labels: documentation :scroll:

#81 Add landmark page fix
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/components/leftBar/LeftBar.tsx
  webapp/src/components/map/Map.tsx
  webapp/src/components/map/stylesheets/addLandmark.css
  webapp/src/components/map/stylesheets/home.css
  webapp/src/pages/addLandmark/AddLandmark.tsx
  webapp/src/pages/addLandmark/addLandmark.css
  webapp/src/pages/home/Home.tsx
  webapp/tsconfig.json
Labels: enhancement :heavy_plus_sign:

#86 Page to see other users' landmarks, and comment and score them
  webapp/src/App.tsx
  webapp/src/components/leftBar/LeftBar.tsx
  webapp/src/components/map/stylesheets/addLandmark.css
  webapp/src/pages/addLandmark/AddLandmark.tsx
  webapp/src/pages/addLandmark/addLandmark.css
  webapp/src/pages/otherUsersLandmark/LandmarkFriend.tsx
  webapp/src/pages/otherUsersLandmark/LandmarkFriendFunctions.tsx
Labels: enhancement :heavy_plus_sign:

#88 Pedro adding locations to solid
  restapi/controllers/landmarks.ts
  restapi/controllers/solid.ts
  restapi/models/Landmark.ts
  restapi/package-lock.json
  restapi/package.json
  restapi/solid/solidLandmark.ts
  webapp/package-lock.json
  webapp/src/shared/shareddtypes.ts
Labels: enhancement :heavy_plus_sign:

#95 Edited friends page
  webapp/src/pages/friends/Friends.tsx
Labels: enhancement :heavy_plus_sign:

#96 Updated the login button
  webapp/src/components/navbar/Navbar.tsx
  webapp/src/components/navbar/navbar.css
Labels: enhancement :heavy_plus_sign:

#100 Added little css to friends and users
  webapp/package-lock.json
  webapp/package.json
  webapp/src/pages/friends/Friends.tsx
  webapp/src/pages/friends/friends.css
  webapp/src/pages/users/users.css
Labels: enhancement :heavy_plus_sign:

#102 Added the new version of the documentation
  images/BuildingBlockView.png
  images/ConceptsDiagram.png
  images/Deployment diagram.png
  images/SequenceDiagramAddLandmark.png
  images/SequenceDiagramFriendsLandmark.png
  images/SequenceDiagramLogging.png
  images/SequenceDiagramLogin.png
  images/UML diagram.png
  images/Use case diagram.png
  images/png.png
  index.html
Labels: documentation :scroll:, enhancement :heavy_plus_sign:, Preparation

#113 Section 09 changed with some design decisions
  docs/09_design_decisions.adoc
Labels: documentation :scroll:

#120 Fixed test issues and added one
  .github/workflows/lomap_en2b.yml
  restapi/controllers/landmarks.ts
  restapi/controllers/users.ts
  sonar-project.properties
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/components/leftBar/LeftBar.tsx
  webapp/src/components/map/Map.tsx
  webapp/src/components/map/MapMarker.tsx
  webapp/src/components/navbar/Navbar.tsx
  webapp/src/index.tsx
  webapp/src/pages/addLandmark/AddLandmark.tsx
  webapp/src/pages/friends/Friends.tsx
  webapp/src/pages/home/Home.tsx
  webapp/src/pages/home/home.css
  webapp/src/pages/login/Login.tsx
  webapp/src/pages/login/login.css
  webapp/src/pages/otherUsersLandmark/LandmarkFriend.tsx
  webapp/src/pages/profile/Profile.tsx
  webapp/src/pages/profile/profile.css
  webapp/src/pages/users/Users.tsx
  webapp/src/reportWebVitals.ts
  webapp/src/setupTests.ts
  webapp/src/test/AddLandmarks.test.tsx
  webapp/src/unused/App.test.tsx
  webapp/src/unused/EmailForm.test.tsx
  webapp/src/unused/EmailForm.tsx
  webapp/src/unused/UserList.test.tsx
  webapp/src/unused/UserList.tsx
  webapp/src/unused/Welcome.test.tsx
  webapp/src/unused/api/userApi.ts
Labels: enhancement :heavy_plus_sign:, Testing

#121 Added more tests
  restapi/controllers/landmarks.ts
  restapi/index.ts
  webapp/src/map/stylesheets/addLandmark.css
  webapp/src/map/stylesheets/home.css
  webapp/src/pages/addLandmark/AddLandmark.tsx
  webapp/src/pages/home/Home.tsx
  webapp/src/pages/otherUsersLandmark/LandmarkFriend.tsx
  webapp/src/test/Home.test.tsx
  webapp/src/test/Login.test.tsx
Labels: enhancement :heavy_plus_sign:, Testing

#122 Documentation update.
  docs/02_architecture_constraints.adoc
  docs/04_solution_strategy.adoc
  docs/05_building_block_view.adoc
  docs/07_deployment_view.adoc
  docs/09_design_decisions.adoc
  docs/12_glossary.adoc
Labels: documentation :scroll:, enhancement :heavy_plus_sign:

#125 Basic tests of restApi
  docs/09_design_decisions.adoc
  restapi/controllers/users.ts
  restapi/package-lock.json
  restapi/tests/api.test.ts
  webapp/package-lock.json
  webapp/src/components/leftBar/LeftBar.tsx
  webapp/src/components/navbar/Navbar.tsx
  webapp/src/pages/addLandmark/AddLandmark.tsx
  webapp/src/pages/friends/Friends.tsx
  webapp/src/pages/users/Users.tsx
  webapp/src/test/Leftbar.test.tsx
  webapp/src/test/Navbar.test.tsx
Labels: Testing

#124 Minor fix to the add landmark page
  webapp/src/pages/addLandmark/AddLandmark.tsx
Labels: enhancement :heavy_plus_sign:

#127 Write landmarks solid
  restapi/package-lock.json
  webapp/package-lock.json
  webapp/src/pages/addLandmark/AddLandmark.tsx
  webapp/src/pages/addLandmark/solidLandmarkManagement.tsx
  webapp/src/shared/shareddtypes.ts
Labels: enhancement :heavy_plus_sign:

#129 Solid integration
  restapi/package-lock.json
  webapp/package-lock.json
  webapp/src/pages/addLandmark/AddLandmark.tsx
  webapp/src/pages/addLandmark/solidLandmarkManagement.tsx
  webapp/src/shared/shareddtypes.ts
Labels: enhancement :heavy_plus_sign:

#130 Improved the UI and added landmark retrieval to it
  webapp/src/pages/addLandmark/AddLandmark.tsx
  webapp/src/pages/addLandmark/solidLandmarkManagement.tsx
  webapp/src/pages/home/Home.tsx
  webapp/src/pages/otherUsersLandmark/LandmarkFriend.tsx
Labels: enhancement :heavy_plus_sign:

#131 Login fixed
  webapp/src/App.tsx
  webapp/src/components/leftBar/LeftBar.tsx
  webapp/src/components/navbar/Navbar.tsx
  webapp/src/pages/friends/Friends.tsx
  webapp/src/pages/login/Login.tsx
  webapp/src/pages/users/Users.tsx
Labels: bug :gear:

#132 Reading from friends and adding them in SOLID.
  webapp/src/pages/addLandmark/solidLandmarkManagement.tsx
Labels: enhancement :heavy_plus_sign:

#133 Landmarks reviews and scores
  webapp/src/pages/addLandmark/solidLandmarkManagement.tsx
  webapp/src/shared/shareddtypes.ts
Labels: enhancement :heavy_plus_sign:
